# role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: expense-trainee
  namespace: expense
rules:
- apiGroups: [""] # "" indicates the core API group like v1 objects such as pods, deployments, services..
  resources: ["pods"]
  verbs: ["get","watch","list"]


# rolebinding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: expense-trainee
  namespace: expense
roleRef: # defining role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: expense-trainee
subjects: # defining user
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: suresh 


# ramesh-admin access
# role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: expense-admin
  namespace: expense
rules:
- apiGroups: ["*"] # * means all
  resources: ["*"]
  verbs: ["*"]

# rolebinding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: expense-admin
  namespace: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: expense-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ramesh